// Code generated by jig; DO NOT EDIT.

//go:generate jig --regen

package test

//jig:name StringStack

type StringStack []string

var zeroString string

//jig:name StringStackPush

func (s *StringStack) Push(v string) {
	*s = append(*s, v)
}

//jig:name StringStackPop

func (s *StringStack) Pop() (string, bool) {
	if len(*s) == 0 {
		return zeroString, false
	}
	i := len(*s) - 1
	v := (*s)[i]
	*s = (*s)[:i]
	return v, true
}
